import React, { useEffect, useState } from "react";
import TextField from "@mui/material/TextField";
import Stack from "@mui/material/Stack";
import Autocomplete from "@mui/material/Autocomplete";
import axios from "axios";

export default function FreeSolo(props) {
  const { setStock, setDetailedStock, setStockChart } = props;
  const [stockAll, setStockAll] = useState([]);

  useEffect(() => {
    // axios
    //   .get(
    //     `https://yfapi.net/v6/finance/quote?region=us&lang=en&symbols=aali.jk`,
    //     { headers: { "X-API-KEY": `nyQb65c2SX2f1JagSg28v3h2UI5I5ZkB20trNC73` } }
    //   )
    //   .then((res) => {
    //     console.log(res.data.quoteResponse.result[0]);
    //     const stock = res.data;
    //     setStockAll({ stock });
    //   });
  }, []);

  const onTagsChange = (event, values) => {
    setStock(values);
    var stockCode = `${values.split("-")[0].trim()}.JK`;
    axios
      .get(
        `https://stock-data-yahoo-finance-alternative.p.rapidapi.com/v11/finance/quoteSummary/${stockCode}`,
        {
          headers: {
            "x-rapidapi-key":
              "90ddd115abmsh679038b600a79a5p111d21jsnbb364698110b",
            "x-rapidapi-host":
              "stock-data-yahoo-finance-alternative.p.rapidapi.com",
            useQueryString: true,
          },
          params: {
            modules:
              "summaryDetail,price,assetProfile,defaultKeyStatistics,earningsTrend",
          },
        }
      )
      .then((res) => {
        const stock = res.data.quoteSummary.result[0];
        setDetailedStock(stock);
      });

    axios
      .get(
        `https://stock-data-yahoo-finance-alternative.p.rapidapi.com/v8/finance/chart/${stockCode}`,
        {
          headers: {
            "x-rapidapi-key":
              "90ddd115abmsh679038b600a79a5p111d21jsnbb364698110b",
            "x-rapidapi-host":
              "stock-data-yahoo-finance-alternative.p.rapidapi.com",
            useQueryString: true,
          },
          params: {
            range: "5mo",
            interval: "1d",
          },
        }
      )
      .then((res) => {
        const stock_chart = res.data.chart.result[0];
        setStockChart(stock_chart);
      });
  };
  return (
    <Stack spacing={2} sx={{ width: 300 }}>
      <Autocomplete
        freeSolo
        id="free-solo-2-demo"
        disableClearable
        options={list_all.map((option) => option)}
        onChange={onTagsChange}
        renderInput={(params) => (
          <TextField
            {...params}
            label="Search input"
            InputProps={{
              ...params.InputProps,
              type: "search",
            }}
          />
        )}
      />
    </Stack>
  );
}

// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
const list_all = [
  "AALI - Astra Agro Lestari Tbk.",
  "ABBA - Mahaka Media Tbk.",
  "ABDA - Asuransi Bina Dana Arta Tbk.",
  "ABMM - ABM Investama Tbk.",
  "ACES - Ace Hardware Indonesia Tbk.",
  "ACST - Acset Indonusa Tbk.",
  "ADES - Akasha Wira International Tbk.",
  "ADHI - Adhi Karya (Persero) Tbk.",
  "ADMF - Adira Dinamika Multi Finance T",
  "ADMG - Polychem Indonesia Tbk",
  "ADRO - Adaro Energy Tbk.",
  "AGAR - Asia Sejahtera Mina Tbk.",
  "AGII - Aneka Gas Industri Tbk.",
  "AGRO - Bank Raya Indonesia Tbk.",
  "AGRS - Bank IBK Indonesia Tbk.",
  "AHAP - Asuransi Harta Aman Pratama Tb",
  "AIMS - Akbar Indo Makmur Stimec Tbk",
  "AISA - FKS Food Sejahtera Tbk.",
  "AKKU - Anugerah Kagum Karya Utama Tbk",
  "AKPI - Argha Karya Prima Industry Tbk",
  "AKRA - AKR Corporindo Tbk.",
  "AKSI - Maming Enam Sembilan Mineral T",
  "ALDO - Alkindo Naratama Tbk.",
  "ALKA - Alakasa Industrindo Tbk",
  "ALMI - Alumindo Light Metal Industry ",
  "ALTO - Tri Banyan Tirta Tbk.",
  "AMAG - Asuransi Multi Artha Guna Tbk.",
  "AMAN - Makmur Berkah Amanda Tbk.",
  "AMAR - Bank Amar Indonesia Tbk.",
  "AMFG - Asahimas Flat Glass Tbk.",
  "AMIN - Ateliers Mecaniques D Indonesi",
  "AMOR - Ashmore Asset Management Indon",
  "AMRT - Sumber Alfaria Trijaya Tbk.",
  "ANDI - Andira Agro Tbk.",
  "ANJT - Austindo Nusantara Jaya Tbk.",
  "ANTM - Aneka Tambang Tbk.",
  "APEX - Apexindo Pratama Duta Tbk.",
  "APIC - Pacific Strategic Financial Tb",
  "APII - Arita Prima Indonesia Tbk.",
  "APLI - Asiaplast Industries Tbk.",
  "APLN - Agung Podomoro Land Tbk.",
  "ARCI - Archi Indonesia Tbk.",
  "ARGO - Argo Pantes Tbk",
  "ARII - Atlas Resources Tbk.",
  "ARKA - Arkha Jayanti Persada Tbk.",
  "ARMY - Armidian Karyatama Tbk.",
  "ARNA - Arwana Citramulia Tbk.",
  "ARTA - Arthavest Tbk",
  "ARTI - Ratu Prabu Energi Tbk",
  "ARTO - Bank Jago Tbk.",
  "ASBI - Asuransi Bintang Tbk.",
  "ASDM - Asuransi Dayin Mitra Tbk.",
  "ASGR - Astra Graphia Tbk.",
  "ASII - Astra International Tbk.",
  "ASJT - Asuransi Jasa Tania Tbk.",
  "ASMI - Asuransi Maximus Graha Persada",
  "ASPI - Andalan Sakti Primaindo Tbk.",
  "ASRI - Alam Sutera Realty Tbk.",
  "ASRM - Asuransi Ramayana Tbk.",
  "ASSA - Adi Sarana Armada Tbk.",
  "ATAP - Trimitra Prawara Goldland Tbk.",
  "ATIC - Anabatic Technologies Tbk.",
  "AUTO - Astra Otoparts Tbk.",
  "AVIA - Avia Avian Tbk.",
  "AYLS - Agro Yasa Lestari Tbk.",
  "BABP - Bank MNC Internasional Tbk.",
  "BACA - Bank Capital Indonesia Tbk.",
  "BAJA - Saranacentral Bajatama Tbk.",
  "BALI - Bali Towerindo Sentra Tbk.",
  "BANK - Bank Aladin Syariah Tbk.",
  "BAPA - Bekasi Asri Pemula Tbk.",
  "BAPI - Bhakti Agung Propertindo Tbk.",
  "BATA - Sepatu Bata Tbk.",
  "BAYU - Bayu Buana Tbk",
  "BBCA - Bank Central Asia Tbk.",
  "BBHI - Allo Bank Indonesia Tbk.",
  "BBKP - Bank KB Bukopin Tbk.",
  "BBLD - Buana Finance Tbk.",
  "BBMD - Bank Mestika Dharma Tbk.",
  "BBNI - Bank Negara Indonesia (Persero",
  "BBRI - Bank Rakyat Indonesia (Persero",
  "BBRM - Pelayaran Nasional Bina Buana ",
  "BBSI - Bank Bisnis Internasional Tbk.",
  "BBSS - Bumi Benowo Sukses Sejahtera T",
  "BBTN - Bank Tabungan Negara (Persero)",
  "BBYB - Bank Neo Commerce Tbk.",
  "BCAP - MNC Kapital Indonesia Tbk.",
  "BCIC - Bank JTrust Indonesia Tbk.",
  "BCIP - Bumi Citra Permai Tbk.",
  "BDMN - Bank Danamon Indonesia Tbk.",
  "BEBS - Berkah Beton Sadaya Tbk.",
  "BEEF - Estika Tata Tiara Tbk.",
  "BEKS - Bank Pembangunan Daerah Banten",
  "BELL - Trisula Textile Industries Tbk",
  "BESS - Batulicin Nusantara Maritim Tb",
  "BEST - Bekasi Fajar Industrial Estate",
  "BFIN - BFI Finance  Indonesia Tbk.",
  "BGTG - Bank Ganesha Tbk.",
  "BHAT - Bhakti Multi Artha Tbk.",
  "BHIT - MNC Investama Tbk.",
  "BIKA - Binakarya Jaya Abadi Tbk.",
  "BIMA - Primarindo Asia Infrastructure",
  "BINA - Bank Ina Perdana Tbk.",
  "BINO - Perma Plasindo Tbk.",
  "BIPI - Astrindo Nusantara Infrastrukt",
  "BIPP - Bhuwanatala Indah Permai Tbk.",
  "BIRD - Blue Bird Tbk.",
  "BISI - BISI International Tbk.",
  "BJBR - Bank Pembangunan Daerah Jawa B",
  "BJTM - Bank Pembangunan Daerah Jawa T",
  "BKDP - Bukit Darmo Property Tbk",
  "BKSL - Sentul City Tbk.",
  "BKSW - Bank QNB Indonesia Tbk.",
  "BLTA - Berlian Laju Tanker Tbk",
  "BLTZ - Graha Layar Prima Tbk.",
  "BLUE - Berkah Prima Perkasa Tbk.",
  "BMAS - Bank Maspion Indonesia Tbk.",
  "BMHS - Bundamedik Tbk.",
  "BMRI - Bank Mandiri (Persero) Tbk.",
  "BMSR - Bintang Mitra Semestaraya Tbk",
  "BMTR - Global Mediacom Tbk.",
  "BNBA - Bank Bumi Arta Tbk.",
  "BNBR - Bakrie & Brothers Tbk",
  "BNGA - Bank CIMB Niaga Tbk.",
  "BNII - Bank Maybank Indonesia Tbk.",
  "BNLI - Bank Permata Tbk.",
  "BOBA - Formosa Ingredient Factory Tbk",
  "BOGA - Bintang Oto Global Tbk.",
  "BOLA - Bali Bintang Sejahtera Tbk.",
  "BOLT - Garuda Metalindo Tbk.",
  "BOSS - Borneo Olah Sarana Sukses Tbk.",
  "BPFI - Batavia Prosperindo Finance Tb",
  "BPII - Batavia Prosperindo Internasio",
  "BPTR - Batavia Prosperindo Trans Tbk.",
  "BRAM - Indo Kordsa Tbk.",
  "BRIS - Bank Syariah Indonesia Tbk.",
  "BRMS - Bumi Resources Minerals Tbk.",
  "BRNA - Berlina Tbk.",
  "BRPT - Barito Pacific Tbk.",
  "BSDE - Bumi Serpong Damai Tbk.",
  "BSIM - Bank Sinarmas Tbk.",
  "BSML - Bintang Samudera Mandiri Lines",
  "BSSR - Baramulti Suksessarana Tbk.",
  "BSWD - Bank Of India Indonesia Tbk.",
  "BTEK - Bumi Teknokultura Unggul Tbk",
  "BTEL - Bakrie Telecom Tbk.",
  "BTON - Betonjaya Manunggal Tbk.",
  "BTPN - Bank BTPN Tbk.",
  "BTPS - Bank BTPN Syariah Tbk.",
  "BUDI - Budi Starch & Sweetener Tbk.",
  "BUKA - Bukalapak.com Tbk.",
  "BUKK - Bukaka Teknik Utama Tbk.",
  "BULL - Buana Lintas Lautan Tbk.",
  "BUMI - Bumi Resources Tbk.",
  "BUVA - Bukit Uluwatu Villa Tbk.",
  "BVIC - Bank Victoria International Tb",
  "BWPT - Eagle High Plantations Tbk.",
  "BYAN - Bayan Resources Tbk.",
  "CAKK - Cahayaputra Asa Keramik Tbk.",
  "CAMP - Campina Ice Cream Industry Tbk",
  "CANI - Capitol Nusantara Indonesia Tb",
  "CARE - Metro Healthcare Indonesia Tbk",
  "CARS - Industri dan Perdagangan Bintr",
  "CASA - Capital Financial Indonesia Tb",
  "CASH - Cashlez Worldwide Indonesia Tb",
  "CASS - Cardig Aero Services Tbk.",
  "CBMF - Cahaya Bintang Medan Tbk.",
  "CCSI - Communication Cable Systems In",
  "CEKA - Wilmar Cahaya Indonesia Tbk.",
  "CENT - Centratama Telekomunikasi Indo",
  "CFIN - Clipan Finance Indonesia Tbk.",
  "CINT - Chitose Internasional Tbk.",
  "CITA - Cita Mineral Investindo Tbk.",
  "CITY - Natura City Developments Tbk.",
  "CLAY - Citra Putra Realty Tbk.",
  "CLEO - Sariguna Primatirta Tbk.",
  "CLPI - Colorpak Indonesia Tbk.",
  "CMNP - Citra Marga Nusaphala Persada ",
  "CMNT - Cemindo Gemilang Tbk.",
  "CMPP - AirAsia Indonesia Tbk.",
  "CMRY - Cisarua Mountain Dairy Tbk.",
  "CNKO - Exploitasi Energi Indonesia Tb",
  "CNTX - Century Textile Industry Tbk.",
  "COCO - Wahana Interfood Nusantara Tbk",
  "COWL - Cowell Development Tbk.",
  "CPIN - Charoen Pokphand Indonesia Tbk",
  "CPRI - Capri Nusa Satu Properti Tbk.",
  "CPRO - Central Proteina Prima Tbk.",
  "CSAP - Catur Sentosa Adiprana Tbk.",
  "CSIS - Cahayasakti Investindo Sukses ",
  "CSMI - Cipta Selera Murni Tbk.",
  "CSRA - Cisadane Sawit Raya Tbk.",
  "CTBN - Citra Tubindo Tbk.",
  "CTRA - Ciputra Development Tbk.",
  "CTTH - Citatah Tbk.",
  "DADA - Diamond Citra Propertindo Tbk.",
  "DART - Duta Anggada Realty Tbk.",
  "DAYA - Duta Intidaya Tbk.",
  "DCII - DCI Indonesia Tbk.",
  "DEAL - Dewata Freightinternational Tb",
  "DEFI - Danasupra Erapacific Tbk.",
  "DEPO - Caturkarda Depo Bangunan Tbk.",
  "DEWA - Darma Henwa Tbk",
  "DFAM - Dafam Property Indonesia Tbk.",
  "DGIK - Nusa Konstruksi Enjiniring Tbk",
  "DGNS - Diagnos Laboratorium Utama Tbk",
  "DIGI - Arkadia Digital Media Tbk.",
  "DILD - Intiland Development Tbk.",
  "DIVA - Distribusi Voucher Nusantara T",
  "DKFT - Central Omega Resources Tbk.",
  "DLTA - Delta Djakarta Tbk.",
  "DMAS - Puradelta Lestari Tbk.",
  "DMMX - Digital Mediatama Maxima Tbk.",
  "DMND - Diamond Food Indonesia Tbk.",
  "DNAR - Bank Oke Indonesia Tbk.",
  "DNET - Indoritel Makmur Internasional",
  "DOID - Delta Dunia Makmur Tbk.",
  "DPNS - Duta Pertiwi Nusantara Tbk.",
  "DPUM - Dua Putra Utama Makmur Tbk.",
  "DRMA - Dharma Polimetal Tbk.",
  "DSFI - Dharma Samudera Fishing Indust",
  "DSNG - Dharma Satya Nusantara Tbk.",
  "DSSA - Dian Swastatika Sentosa Tbk",
  "DUCK - Jaya Bersama Indo Tbk.",
  "DUTI - Duta Pertiwi Tbk",
  "DVLA - Darya-Varia Laboratoria Tbk.",
  "DWGL - Dwi Guna Laksana Tbk.",
  "DYAN - Dyandra Media International Tb",
  "EAST - Eastparc Hotel Tbk.",
  "ECII - Electronic City Indonesia Tbk.",
  "EDGE - Indointernet Tbk.",
  "EKAD - Ekadharma International Tbk.",
  "ELSA - Elnusa Tbk.",
  "ELTY - Bakrieland Development Tbk.",
  "EMDE - Megapolitan Developments Tbk.",
  "EMTK - Elang Mahkota Teknologi Tbk.",
  "ENRG - Energi Mega Persada Tbk.",
  "ENVY - Envy Technologies Indonesia Tb",
  "ENZO - Morenzo Abadi Perkasa Tbk.",
  "EPAC - Megalestari Epack Sentosaraya ",
  "EPMT - Enseval Putera Megatrading Tbk",
  "ERAA - Erajaya Swasembada Tbk.",
  "ERTX - Eratex Djaja Tbk.",
  "ESIP - Sinergi Inti Plastindo Tbk.",
  "ESSA - Surya Esa Perkasa Tbk.",
  "ESTA - Esta Multi Usaha Tbk.",
  "ESTI - Ever Shine Tex Tbk.",
  "ETWA - Eterindo Wahanatama Tbk",
  "EXCL - XL Axiata Tbk.",
  "FAPA - FAP Agri Tbk.",
  "FAST - Fast Food Indonesia Tbk.",
  "FASW - Fajar Surya Wisesa Tbk.",
  "FILM - MD Pictures Tbk.",
  "FIMP - Fimperkasa Utama Tbk.",
  "FIRE - Alfa Energi Investama Tbk.",
  "FISH - FKS Multi Agro Tbk.",
  "FITT - Hotel Fitra International Tbk.",
  "FLMC - Falmaco Nonwoven Industri Tbk.",
  "FMII - Fortune Mate Indonesia Tbk",
  "FOOD - Sentra Food Indonesia Tbk.",
  "FORU - Fortune Indonesia Tbk",
  "FORZ - Forza Land Indonesia Tbk.",
  "FPNI - Lotte Chemical Titan Tbk.",
  "FREN - Smartfren Telecom Tbk.",
  "FUJI - Fuji Finance Indonesia Tbk.",
  "GAMA - Aksara Global Development Tbk.",
  "GDST - Gunawan Dianjaya Steel Tbk.",
  "GDYR - Goodyear Indonesia Tbk.",
  "GEMA - Gema Grahasarana Tbk.",
  "GEMS - Golden Energy Mines Tbk.",
  "GGRM - Gudang Garam Tbk.",
  "GGRP - Gunung Raja Paksi Tbk.",
  "GHON - Gihon Telekomunikasi Indonesia",
  "GIAA - Garuda Indonesia (Persero) Tbk",
  "GJTL - Gajah Tunggal Tbk.",
  "GLOB - Globe Kita Terang Tbk.",
  "GLVA - Galva Technologies Tbk.",
  "GMFI - Garuda Maintenance Facility Ae",
  "GMTD - Gowa Makassar Tourism Developm",
  "GOLD - Visi Telekomunikasi Infrastruk",
  "GOLL - Golden Plantation Tbk.",
  "GOOD - Garudafood Putra Putri Jaya Tb",
  "GPRA - Perdana Gapuraprima Tbk.",
  "GPSO - Geoprima Solusi Tbk.",
  "GSMF - Equity Development Investment ",
  "GTBO - Garda Tujuh Buana Tbk",
  "GTSI - GTS Internasional Tbk.",
  "GWSA - Greenwood Sejahtera Tbk.",
  "GZCO - Gozco Plantations Tbk.",
  "HADE - Himalaya Energi Perkasa Tbk.",
  "HAIS - Hasnur Internasional Shipping ",
  "HDFA - Radana Bhaskara Finance Tbk.",
  "HDIT - Hensel Davest Indonesia Tbk.",
  "HDTX - Panasia Indo Resources Tbk.",
  "HEAL - Medikaloka Hermina Tbk.",
  "HELI - Jaya Trishindo Tbk.",
  "HERO - Hero Supermarket Tbk.",
  "HEXA - Hexindo Adiperkasa Tbk.",
  "HITS - Humpuss Intermoda Transportasi",
  "HKMU - HK Metals Utama Tbk.",
  "HMSP - H.M. Sampoerna Tbk.",
  "HOKI - Buyung Poetra Sembada Tbk.",
  "HOME - Hotel Mandarine Regency Tbk.",
  "HOMI - Grand House Mulia Tbk.",
  "HOPE - Harapan Duta Pertiwi Tbk.",
  "HOTL - Saraswati Griya Lestari Tbk.",
  "HRME - Menteng Heritage Realty Tbk.",
  "HRTA - Hartadinata Abadi Tbk.",
  "HRUM - Harum Energy Tbk.",
  "IATA - Indonesia Transport & Infrastr",
  "IBFN - Intan Baruprana Finance Tbk.",
  "IBST - Inti Bangun Sejahtera Tbk.",
  "ICBP - Indofood CBP Sukses Makmur Tbk",
  "ICON - Island Concepts Indonesia Tbk.",
  "IDEA - Idea Indonesia Akademi Tbk.",
  "IDPR - Indonesia Pondasi Raya Tbk.",
  "IFII - Indonesia Fibreboard Industry ",
  "IFSH - Ifishdeco Tbk.",
  "IGAR - Champion Pacific Indonesia Tbk",
  "IIKP - Inti Agri Resources Tbk",
  "IKAI - Intikeramik Alamasri Industri ",
  "IKAN - Era Mandiri Cemerlang Tbk.",
  "IKBI - Sumi Indo Kabel Tbk.",
  "IMAS - Indomobil Sukses Internasional",
  "IMJS - Indomobil Multi Jasa Tbk.",
  "IMPC - Impack Pratama Industri Tbk.",
  "INAF - Indofarma Tbk.",
  "INAI - Indal Aluminium Industry Tbk.",
  "INCF - Indo Komoditi Korpora Tbk.",
  "INCI - Intanwijaya Internasional Tbk",
  "INCO - Vale Indonesia Tbk.",
  "INDF - Indofood Sukses Makmur Tbk.",
  "INDO - Royalindo Investa Wijaya Tbk.",
  "INDR - Indo-Rama Synthetics Tbk.",
  "INDS - Indospring Tbk.",
  "INDX - Tanah Laut Tbk",
  "INDY - Indika Energy Tbk.",
  "INKP - Indah Kiat Pulp & Paper Tbk.",
  "INOV - Inocycle Technology Group Tbk.",
  "INPC - Bank Artha Graha Internasional",
  "INPP - Indonesian Paradise Property T",
  "INPS - Indah Prakasa Sentosa Tbk.",
  "INRU - Toba Pulp Lestari Tbk.",
  "INTA - Intraco Penta Tbk.",
  "INTD - Inter Delta Tbk",
  "INTP - Indocement Tunggal Prakarsa Tb",
  "IPAC - Era Graharealty Tbk.",
  "IPCC - Indonesia Kendaraan Terminal T",
  "IPCM - Jasa Armada Indonesia Tbk.",
  "IPOL - Indopoly Swakarsa Industry Tbk",
  "IPPE - Indo Pureco Pratama Tbk.",
  "IPTV - MNC Vision Networks Tbk.",
  "IRRA - Itama Ranoraya Tbk.",
  "ISAT - Indosat Tbk.",
  "ISSP - Steel Pipe Industry of Indones",
  "ITIC - Indonesian Tobacco Tbk.",
  "ITMA - Sumber Energi Andalan Tbk.",
  "ITMG - Indo Tambangraya Megah Tbk.",
  "JAST - Jasnita Telekomindo Tbk.",
  "JAWA - Jaya Agra Wattie Tbk.",
  "JAYA - Armada Berjaya Trans Tbk.",
  "JECC - Jembo Cable Company Tbk.",
  "JGLE - Graha Andrasentra Propertindo ",
  "JIHD - Jakarta International Hotels &",
  "JKON - Jaya Konstruksi Manggala Prata",
  "JKSW - Jakarta Kyoei Steel Works Tbk.",
  "JMAS - Asuransi Jiwa Syariah Jasa Mit",
  "JPFA - Japfa Comfeed Indonesia Tbk.",
  "JRPT - Jaya Real Property Tbk.",
  "JSKY - Sky Energy Indonesia Tbk.",
  "JSMR - Jasa Marga (Persero) Tbk.",
  "JSPT - Jakarta Setiabudi Internasiona",
  "JTPE - Jasuindo Tiga Perkasa Tbk.",
  "KAEF - Kimia Farma Tbk.",
  "KARW - ICTSI Jasa Prima Tbk.",
  "KAYU - Darmi Bersaudara Tbk.",
  "KBAG - Karya Bersama Anugerah Tbk.",
  "KBLI - KMI Wire & Cable Tbk.",
  "KBLM - Kabelindo Murni Tbk.",
  "KBLV - First Media Tbk.",
  "KBRI - Kertas Basuki Rachmat Indonesi",
  "KDSI - Kedawung Setia Industrial Tbk.",
  "KEEN - Kencana Energi Lestari Tbk.",
  "KEJU - Mulia Boga Raya Tbk.",
  "KIAS - Keramika Indonesia Assosiasi T",
  "KICI - Kedaung Indah Can Tbk",
  "KIJA - Kawasan Industri Jababeka Tbk.",
  "KINO - Kino Indonesia Tbk.",
  "KIOS - Kioson Komersial Indonesia Tbk",
  "KJEN - Krida Jaringan Nusantara Tbk.",
  "KKGI - Resource Alam Indonesia Tbk.",
  "KLBF - Kalbe Farma Tbk.",
  "KMDS - Kurniamitra Duta Sentosa Tbk.",
  "KMTR - Kirana Megatara Tbk.",
  "KOBX - Kobexindo Tractors Tbk.",
  "KOIN - Kokoh Inti Arebama Tbk",
  "KONI - Perdana Bangun Pusaka Tbk",
  "KOPI - Mitra Energi Persada Tbk.",
  "KOTA - DMS Propertindo Tbk.",
  "KPAL - Steadfast Marine Tbk.",
  "KPAS - Cottonindo Ariesta Tbk.",
  "KPIG - MNC Land Tbk.",
  "KRAH - Grand Kartech Tbk.",
  "KRAS - Krakatau Steel (Persero) Tbk.",
  "KREN - Kresna Graha Investama Tbk.",
  "KUAS - Ace Oldfields Tbk.",
  "LABA - Ladangbaja Murni Tbk.",
  "LAND - Trimitra Propertindo Tbk.",
  "LAPD - Leyand International Tbk.",
  "LCGP - Eureka Prima Jakarta Tbk.",
  "LCKM - LCK Global Kedaton Tbk.",
  "LEAD - Logindo Samudramakmur Tbk.",
  "LFLO - Imago Mulia Persada Tbk.",
  "LIFE - Asuransi Jiwa Sinarmas MSIG Tb",
  "LINK - Link Net Tbk.",
  "LION - Lion Metal Works Tbk.",
  "LMAS - Limas Indonesia Makmur Tbk",
  "LMPI - Langgeng Makmur Industri Tbk.",
  "LMSH - Lionmesh Prima Tbk.",
  "LPCK - Lippo Cikarang Tbk",
  "LPGI - Lippo General Insurance Tbk.",
  "LPIN - Multi Prima Sejahtera Tbk",
  "LPKR - Lippo Karawaci Tbk.",
  "LPLI - Star Pacific Tbk",
  "LPPF - Matahari Department Store Tbk.",
  "LPPS - Lenox Pasifik Investama Tbk.",
  "LRNA - Eka Sari Lorena Transport Tbk.",
  "LSIP - PP London Sumatra Indonesia Tb",
  "LTLS - Lautan Luas Tbk.",
  "LUCK - Sentral Mitra Informatika Tbk.",
  "LUCY - Lima Dua Lima Tiga Tbk.",
  "MABA - Marga Abhinaya Abadi Tbk.",
  "MAGP - Multi Agro Gemilang Plantation",
  "MAIN - Malindo Feedmill Tbk.",
  "MAMI - Mas Murni Indonesia Tbk",
  "MAPA - Map Aktif Adiperkasa Tbk.",
  "MAPB - MAP Boga Adiperkasa Tbk.",
  "MAPI - Mitra Adiperkasa Tbk.",
  "MARI - Mahaka Radio Integra Tbk.",
  "MARK - Mark Dynamics Indonesia Tbk.",
  "MASA - Multistrada Arah Sarana Tbk.",
  "MASB - Bank Multiarta Sentosa Tbk.",
  "MAYA - Bank Mayapada Internasional Tb",
  "MBAP - Mitrabara Adiperdana Tbk.",
  "MBSS - Mitrabahtera Segara Sejati Tbk",
  "MBTO - Martina Berto Tbk.",
  "MCAS - M Cash Integrasi Tbk.",
  "MCOL - Prima Andalan Mandiri Tbk.",
  "MCOR - Bank China Construction Bank I",
  "MDIA - Intermedia Capital Tbk.",
  "MDKA - Merdeka Copper Gold Tbk.",
  "MDKI - Emdeki Utama Tbk.",
  "MDLN - Modernland Realty Tbk.",
  "MDRN - Modern Internasional Tbk.",
  "MEDC - Medco Energi Internasional Tbk",
  "MEGA - Bank Mega Tbk.",
  "MERK - Merck Tbk.",
  "META - Nusantara Infrastructure Tbk.",
  "MFIN - Mandala Multifinance Tbk.",
  "MFMI - Multifiling Mitra Indonesia Tb",
  "MGLV - Panca Anugrah Wisesa Tbk.",
  "MGNA - Magna Investama Mandiri Tbk.",
  "MGRO - Mahkota Group Tbk.",
  "MICE - Multi Indocitra Tbk.",
  "MIDI - Midi Utama Indonesia Tbk.",
  "MIKA - Mitra Keluarga Karyasehat Tbk.",
  "MINA - Sanurhasta Mitra Tbk.",
  "MIRA - Mitra International Resources ",
  "MITI - Mitra Investindo Tbk.",
  "MKNT - Mitra Komunikasi Nusantara Tbk",
  "MKPI - Metropolitan Kentjana Tbk.",
  "MLBI - Multi Bintang Indonesia Tbk.",
  "MLIA - Mulia Industrindo Tbk",
  "MLPL - Multipolar Tbk.",
  "MLPT - Multipolar Technology Tbk.",
  "MMLP - Mega Manunggal Property Tbk.",
  "MNCN - Media Nusantara Citra Tbk.",
  "MOLI - Madusari Murni Indah Tbk.",
  "MPMX - Mitra Pinasthika Mustika Tbk.",
  "MPOW - Megapower Makmur Tbk.",
  "MPPA - Matahari Putra Prima Tbk.",
  "MPRO - Maha Properti Indonesia Tbk.",
  "MRAT - Mustika Ratu Tbk.",
  "MREI - Maskapai Reasuransi Indonesia ",
  "MSIN - MNC Studios International Tbk.",
  "MSKY - MNC Sky Vision Tbk.",
  "MTDL - Metrodata Electronics Tbk.",
  "MTEL - Dayamitra Telekomunikasi Tbk.",
  "MTFN - Capitalinc Investment Tbk.",
  "MTLA - Metropolitan Land Tbk.",
  "MTPS - Meta Epsi Tbk.",
  "MTRA - Mitra Pemuda Tbk.",
  "MTSM - Metro Realty Tbk.",
  "MTWI - Malacca Trust Wuwungan Insuran",
  "MYOH - Samindo Resources Tbk.",
  "MYOR - Mayora Indah Tbk.",
  "MYRX - Hanson International Tbk.",
  "MYTX - Asia Pacific Investama Tbk.",
  "NASA - Andalan Perkasa Abadi Tbk.",
  "NASI - Wahana Inti Makmur Tbk.",
  "NATO - Surya Permata Andalan Tbk.",
  "NELY - Pelayaran Nelly Dwi Putri Tbk.",
  "NFCX - NFC Indonesia Tbk.",
  "NICK - Charnic Capital Tbk.",
  "NICL - PAM Mineral Tbk.",
  "NIKL - Pelat Timah Nusantara Tbk.",
  "NIPS - Nipress Tbk.",
  "NIRO - City Retail Developments Tbk.",
  "NISP - Bank OCBC NISP Tbk.",
  "NOBU - Bank Nationalnobu Tbk.",
  "NPGF - Nusa Palapa Gemilang Tbk.",
  "NRCA - Nusa Raya Cipta Tbk.",
  "NUSA - Sinergi Megah Internusa Tbk.",
  "NZIA - Nusantara Almazia Tbk.",
  "OASA - Protech Mitra Perkasa Tbk.",
  "OBMD - OBM Drilchem Tbk.",
  "OCAP - Onix Capital Tbk.",
  "OILS - Indo Oil Perkasa Tbk.",
  "OKAS - Ancora Indonesia Resources Tbk",
  "OMRE - Indonesia Prima Property Tbk",
  "OPMS - Optima Prima Metal Sinergi Tbk",
  "PADI - Minna Padi Investama Sekuritas",
  "PALM - Provident Agro Tbk.",
  "PAMG - Bima Sakti Pertiwi Tbk.",
  "PANI - Pratama Abadi Nusa Industri Tb",
  "PANR - Panorama Sentrawisata Tbk.",
  "PANS - Panin Sekuritas Tbk.",
  "PBID - Panca Budi Idaman Tbk.",
  "PBRX - Pan Brothers Tbk.",
  "PBSA - Paramita Bangun Sarana Tbk.",
  "PCAR - Prima Cakrawala Abadi Tbk.",
  "PDES - Destinasi Tirta Nusantara Tbk",
  "PEGE - Panca Global Kapital Tbk.",
  "PEHA - Phapros Tbk.",
  "PGAS - Perusahaan Gas Negara Tbk.",
  "PGJO - Tourindo Guide Indonesia Tbk.",
  "PGLI - Pembangunan Graha Lestari Inda",
  "PGUN - Pradiksi Gunatama Tbk.",
  "PICO - Pelangi Indah Canindo Tbk",
  "PJAA - Pembangunan Jaya Ancol Tbk.",
  "PKPK - Perdana Karya Perkasa Tbk",
  "PLAN - Planet Properindo Jaya Tbk.",
  "PLAS - Polaris Investama Tbk",
  "PLIN - Plaza Indonesia Realty Tbk.",
  "PMJS - Putra Mandiri Jembar Tbk.",
  "PMMP - Panca Mitra Multiperdana Tbk.",
  "PNBN - Bank Pan Indonesia Tbk",
  "PNBS - Bank Panin Dubai Syariah Tbk.",
  "PNGO - Pinago Utama Tbk.",
  "PNIN - Paninvest Tbk.",
  "PNLF - Panin Financial Tbk.",
  "PNSE - Pudjiadi & Sons Tbk.",
  "POLA - Pool Advista Finance Tbk.",
  "POLI - Pollux Hotels Group Tbk.",
  "POLL - Pollux Properties Indonesia Tb",
  "POLU - Golden Flower Tbk.",
  "POLY - Asia Pacific Fibers Tbk",
  "POOL - Pool Advista Indonesia Tbk.",
  "PORT - Nusantara Pelabuhan Handal Tbk",
  "POSA - Bliss Properti Indonesia Tbk.",
  "POWR - Cikarang Listrindo Tbk.",
  "PPGL - Prima Globalindo Logistik Tbk.",
  "PPRE - PP Presisi Tbk.",
  "PPRO - PP Properti Tbk.",
  "PRAS - Prima Alloy Steel Universal Tb",
  "PRDA - Prodia Widyahusada Tbk.",
  "PRIM - Royal Prima Tbk.",
  "PSAB - J Resources Asia Pasifik Tbk.",
  "PSDN - Prasidha Aneka Niaga Tbk",
  "PSGO - Palma Serasih Tbk.",
  "PSKT - Red Planet Indonesia Tbk.",
  "PSSI - Pelita Samudera Shipping Tbk.",
  "PTBA - Bukit Asam Tbk.",
  "PTDU - Djasa Ubersakti Tbk.",
  "PTIS - Indo Straits Tbk.",
  "PTPP - PP (Persero) Tbk.",
  "PTPW - Pratama Widya Tbk.",
  "PTRO - Petrosea Tbk.",
  "PTSN - Sat Nusapersada Tbk",
  "PTSP - Pioneerindo Gourmet Internatio",
  "PUDP - Pudjiadi Prestige Tbk.",
  "PURA - Putra Rajawali Kencana Tbk.",
  "PURE - Trinitan Metals and Minerals T",
  "PURI - Puri Global Sukses Tbk.",
  "PWON - Pakuwon Jati Tbk.",
  "PYFA - Pyridam Farma Tbk",
  "PZZA - Sarimelati Kencana Tbk.",
  "RAJA - Rukun Raharja Tbk.",
  "RALS - Ramayana Lestari Sentosa Tbk.",
  "RANC - Supra Boga Lestari Tbk.",
  "RBMS - Ristia Bintang Mahkotasejati T",
  "RDTX - Roda Vivatex Tbk",
  "REAL - Repower Asia Indonesia Tbk.",
  "RELI - Reliance Sekuritas Indonesia T",
  "RICY - Ricky Putra Globalindo Tbk",
  "RIGS - Rig Tenders Indonesia Tbk.",
  "RIMO - Rimo International Lestari Tbk",
  "RISE - Jaya Sukses Makmur Sentosa Tbk",
  "RMBA - Bentoel Internasional Investam",
  "RMKE - RMK Energy Tbk.",
  "ROCK - Rockfields Properti Indonesia ",
  "RODA - Pikko Land Development Tbk.",
  "RONY - Aesler Grup Internasional Tbk.",
  "ROTI - Nippon Indosari Corpindo Tbk.",
  "RSGK - Kedoya Adyaraya Tbk.",
  "RUIS - Radiant Utama Interinsco Tbk.",
  "RUNS - Global Sukses Solusi Tbk.",
  "SAFE - Steady Safe Tbk",
  "SAME - Sarana Meditama Metropolitan T",
  "SAMF - Saraswanti Anugerah Makmur Tbk",
  "SAPX - Satria Antaran Prima Tbk.",
  "SATU - Kota Satu Properti Tbk.",
  "SBAT - Sejahtera Bintang Abadi Textil",
  "SBMA - Surya Biru Murni Acetylene Tbk",
  "SCCO - Supreme Cable Manufacturing & ",
  "SCMA - Surya Citra Media Tbk.",
  "SCNP - Selaras Citra Nusantara Perkas",
  "SCPI - Organon Pharma Indonesia Tbk.",
  "SDMU - Sidomulyo Selaras Tbk.",
  "SDPC - Millennium Pharmacon Internati",
  "SDRA - Bank Woori Saudara Indonesia 1",
  "SFAN - Surya Fajar Capital Tbk.",
  "SGER - Sumber Global Energy Tbk.",
  "SGRO - Sampoerna Agro Tbk.",
  "SHID - Hotel Sahid Jaya International",
  "SHIP - Sillo Maritime Perdana Tbk.",
  "SIDO - Industri Jamu dan Farmasi Sido",
  "SILO - Siloam International Hospitals",
  "SIMA - Siwani Makmur Tbk",
  "SIMP - Salim Ivomas Pratama Tbk.",
  "SINI - Singaraja Putra Tbk.",
  "SIPD - Sreeya Sewu Indonesia Tbk.",
  "SKBM - Sekar Bumi Tbk.",
  "SKLT - Sekar Laut Tbk.",
  "SKRN - Superkrane Mitra Utama Tbk.",
  "SKYB - Northcliff Citranusa Indonesia",
  "SLIS - Gaya Abadi Sempurna Tbk.",
  "SMAR - Smart Tbk.",
  "SMBR - Semen Baturaja (Persero) Tbk.",
  "SMCB - Solusi Bangun Indonesia Tbk.",
  "SMDM - Suryamas Dutamakmur Tbk.",
  "SMDR - Samudera Indonesia  Tbk.",
  "SMGR - Semen Indonesia (Persero) Tbk.",
  "SMKL - Satyamitra Kemas Lestari Tbk.",
  "SMMA - Sinarmas Multiartha Tbk.",
  "SMMT - Golden Eagle Energy Tbk.",
  "SMRA - Summarecon Agung Tbk.",
  "SMRU - SMR Utama Tbk.",
  "SMSM - Selamat Sempurna Tbk.",
  "SNLK - Sunter Lakeside Hotel Tbk.",
  "SOCI - Soechi Lines Tbk.",
  "SOFA - Boston Furniture Industries Tb",
  "SOHO - Soho Global Health Tbk.",
  "SONA - Sona Topas Tourism Industry Tb",
  "SOSS - Shield On Service Tbk.",
  "SOTS - Satria Mega Kencana Tbk.",
  "SPMA - Suparma Tbk.",
  "SPTO - Surya Pertiwi Tbk.",
  "SQMI - Wilton Makmur Indonesia Tbk.",
  "SRAJ - Sejahteraraya Anugrahjaya Tbk.",
  "SRIL - Sri Rejeki Isman Tbk.",
  "SRSN - Indo Acidatama Tbk",
  "SRTG - Saratoga Investama Sedaya Tbk.",
  "SSIA - Surya Semesta Internusa Tbk.",
  "SSMS - Sawit Sumbermas Sarana Tbk.",
  "SSTM - Sunson Textile Manufacture Tbk",
  "STAR - Buana Artha Anugerah Tbk.",
  "STTP - Siantar Top Tbk.",
  "SUGI - Sugih Energy Tbk.",
  "SULI - SLJ Global Tbk.",
  "SUPR - Solusi Tunas Pratama Tbk.",
  "SURE - Super Energy Tbk.",
  "SWAT - Sriwahana Adityakarta Tbk.",
  "TALF - Tunas Alfin Tbk.",
  "TAMA - Lancartama Sejati Tbk.",
  "TAMU - Pelayaran Tamarin Samudra Tbk.",
  "TAPG - Triputra Agro Persada Tbk.",
  "TARA - Agung Semesta Sejahtera Tbk.",
  "TAXI - Express Transindo Utama Tbk.",
  "TAYS - Jaya Swarasa Agung Tbk.",
  "TBIG - Tower Bersama Infrastructure T",
  "TBLA - Tunas Baru Lampung Tbk.",
  "TBMS - Tembaga Mulia Semanan Tbk.",
  "TCID - Mandom Indonesia Tbk.",
  "TCPI - Transcoal Pacific Tbk.",
  "TDPM - Tridomain Performance Material",
  "TEBE - Dana Brata Luhur Tbk.",
  "TECH - Indosterling Technomedia Tbk.",
  "TELE - Tiphone Mobile Indonesia Tbk.",
  "TFAS - Telefast Indonesia Tbk.",
  "TFCO - Tifico Fiber Indonesia Tbk.",
  "TGKA - Tigaraksa Satria Tbk.",
  "TGRA - Terregra Asia Energy Tbk.",
  "TIFA - KDB Tifa Finance Tbk.",
  "TINS - Timah Tbk.",
  "TIRA - Tira Austenite Tbk",
  "TIRT - Tirta Mahakam Resources Tbk",
  "TKIM - Pabrik Kertas Tjiwi Kimia Tbk.",
  "TLKM - Telkom Indonesia (Persero) Tbk",
  "TMAS - Temas Tbk.",
  "TMPO - Tempo Intimedia Tbk.",
  "TNCA - Trimuda Nuansa Citra Tbk.",
  "TOBA - TBS Energi Utama Tbk.",
  "TOPS - Totalindo Eka Persada Tbk.",
  "TOTL - Total Bangun Persada Tbk.",
  "TOTO - Surya Toto Indonesia Tbk.",
  "TOWR - Sarana Menara Nusantara Tbk.",
  "TOYS - Sunindo Adipersada Tbk.",
  "TPIA - Chandra Asri Petrochemical Tbk",
  "TPMA - Trans Power Marine Tbk.",
  "TRAM - Trada Alam Minera Tbk.",
  "TRIL - Triwira Insanlestari Tbk.",
  "TRIM - Trimegah Sekuritas Indonesia T",
  "TRIN - Perintis Triniti Properti Tbk.",
  "TRIO - Trikomsel Oke Tbk.",
  "TRIS - Trisula International Tbk.",
  "TRJA - Transkon Jaya Tbk.",
  "TRST - Trias Sentosa Tbk.",
  "TRUE - Triniti Dinamik Tbk.",
  "TRUK - Guna Timur Raya Tbk.",
  "TRUS - Trust Finance Indonesia Tbk",
  "TSPC - Tempo Scan Pacific Tbk.",
  "TUGU - Asuransi Tugu Pratama Indonesi",
  "TURI - Tunas Ridean Tbk.",
  "UANG - Pakuan Tbk.",
  "UCID - Uni-Charm Indonesia Tbk.",
  "UFOE - Damai Sejahtera Abadi Tbk.",
  "ULTJ - Ultra Jaya Milk Industry & Tra",
  "UNIC - Unggul Indah Cahaya Tbk.",
  "UNIQ - Ulima Nitra Tbk.",
  "UNIT - Nusantara Inti Corpora Tbk",
  "UNSP - Bakrie Sumatera Plantations Tb",
  "UNTR - United Tractors Tbk.",
  "UNVR - Unilever Indonesia Tbk.",
  "URBN - Urban Jakarta Propertindo Tbk.",
  "UVCR - Trimegah Karya Pratama Tbk.",
  "VICI - Victoria Care Indonesia Tbk.",
  "VICO - Victoria Investama Tbk.",
  "VINS - Victoria Insurance Tbk.",
  "VIVA - Visi Media Asia Tbk.",
  "VOKS - Voksel Electric Tbk.",
  "VRNA - Verena Multi Finance Tbk.",
  "WAPO - Wahana Pronatural Tbk.",
  "WEGE - Wijaya Karya Bangunan Gedung T",
  "WEHA - WEHA Transportasi Indonesia Tb",
  "WGSH - Wira Global Solusi Tbk.",
  "WICO - Wicaksana Overseas Internation",
  "WIFI - Solusi Sinergi Digital Tbk.",
  "WIIM - Wismilak Inti Makmur Tbk.",
  "WIKA - Wijaya Karya (Persero) Tbk.",
  "WINS - Wintermar Offshore Marine Tbk.",
  "WMPP - Widodo Makmur Perkasa Tbk.",
  "WMUU - Widodo Makmur Unggas Tbk.",
  "WOMF - Wahana Ottomitra Multiartha Tb",
  "WOOD - Integra Indocabinet Tbk.",
  "WOWS - Ginting Jaya Energi Tbk.",
  "WSBP - Waskita Beton Precast Tbk.",
  "WSKT - Waskita Karya (Persero) Tbk.",
  "WTON - Wijaya Karya Beton Tbk.",
  "YELO - Yelooo Integra Datanet Tbk.",
  "YPAS - Yanaprima Hastapersada Tbk",
  "YULE - Yulie Sekuritas Indonesia Tbk.",
  "ZBRA - Zebra Nusantara Tbk",
  "ZINC - Kapuas Prima Coal Tbk.",
  "ZONE - Mega Perintis Tbk.",
  "ZYRX - Zyrexindo Mandiri Buana Tbk.",
];
